### ISSUE TITLE
Error during benchmark run: This operation is not supported for complex128 values because it would be ambiguous.

### ISSUE THREAD

**Issue by MartinMeilinger** [QUARK-framework/QUARK#49]
There seems to be a bug somewhere in the code when running this configuration (full config below):
```
TSP -> Ising -> qiskit -> QAOA -> Powell
```
At the end of the run, a `TypeError` is thrown:
```
TypeError: ufunc 'signbit' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
directly causing:
```
TypeError: This operation is not supported for complex128 values because it would be ambiguous.
```
(see Traceback at the end of [logger.log](https://github.com/QUARK-framework/QUARK/files/11337631/logger.log))
As far as I can see, some complex value(s) end(s) up somewhere it/they shouldn't, but I have no idea how or why.
I clicked a bit through the lines mentioned in the Traceback, but couldn't find what's causing the problem.

full config:
```
application:
  config:
    nodes:
    - 3
  name: TSP
mapping:
  Ising:
    config:
      lagrange_factor:
      - 1.0
      mapping:
      - qiskit
    solver:
    - config:
        depth:
        - 3
        opt_method:
        - Powell
        shots:
        - 10
      device:
      - LocalSimulator
      name: QAOA
repetitions: 1
```
